{{- range .Values.jxRequirements.environments }}
{{- if not .ingress.tls.production }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-{{ .ingress.domain | replace "." "-" }}-s"
  labels:
    jenkins.io/letsencrypt-service: letsencrypt-staging
spec:
  secretName: "tls-{{ .ingress.domain | replace "." "-" }}-s"
  issuerRef:
    name: letsencrypt-staging
{{- if $.Values.issuer.cluster }}
    kind: ClusterIssuer
{{- end }}
  commonName: "*.{{ .ingress.domain }}"
  dnsNames:
  - "*.{{ .ingress.domain }}"
  - "{{ .ingress.domain }}"
{{- end }}
{{- end }}