
# generated by: jx gitops variables
export APP_NAME='acme-environments'
export BRANCH_NAME='master'
export BUILD_NUMBER='1'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='gcr.io'
export DOCKER_REGISTRY_ORG='tfapi-6b146'
export DOMAIN='jx.tf-api.com'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard.jx.tf-api.com/thoughtforge-ai/acme-environments/master/1'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='gcr.io/tfapi-6b146/acme-environments:0.0.5'
export NAMESPACE_SUB_DOMAIN='.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='gcr.io'
export REPO_NAME='acme-environments'
export REPO_OWNER='thoughtforge-ai'
export VERSION='0.0.5'


# content from git...

# generated by: jx gitops variables
export APP_NAME='acme-environments'
export BRANCH_NAME='master'
export BUILD_NUMBER='10'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='gcr.io'
export DOCKER_REGISTRY_ORG='tfapi-6b146'
export DOMAIN='jx.tf-api.com'
export GIT_BRANCH='HEAD'
export JENKINS_X_URL='https://dashboard.jx.tf-api.com/thoughtforge-ai/acme-environments/master/10'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export MINK_AS='tekton-bot'
export MINK_IMAGE='gcr.io/tfapi-6b146/acme-environments:0.0.4'
export NAMESPACE_SUB_DOMAIN='.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='gcr.io'
export REPO_NAME='acme-environments'
export REPO_OWNER='thoughtforge-ai'
export VERSION='0.0.4'


